function [I1,I2] = ElementalStiffnessD(gdshape,duNdx,duNdy,tN11,...
    tN12,tN21,tN22,detJ,w2D)

[duNdx,dvNdx] = ExtractVectorComponents(duNdx);
[duNdy,dvNdy] = ExtractVectorComponents(duNdy);

I1 = 0.5*(squeeze(gdshape(1,:,:))*(tN11.*(detJ.*w2D)) + ...
    squeeze(gdshape(1,:,:))*(tN11.*(detJ.*w2D)) + ...
    squeeze(gdshape(2,:,:))*(tN12.*(detJ.*w2D)) + ...
    squeeze(gdshape(2,:,:))*(tN21.*(detJ.*w2D))) - ...
    squeeze(gdshape(1,:,:))*(duNdx.*(detJ.*w2D)) - ...
    squeeze(gdshape(2,:,:))*(duNdy.*(detJ.*w2D));

I2 = 0.5*(squeeze(gdshape(1,:,:))*(tN12.*(detJ.*w2D)) + ...
    squeeze(gdshape(1,:,:))*(tN21.*(detJ.*w2D)) + ...
    squeeze(gdshape(2,:,:))*(tN22.*(detJ.*w2D)) + ...
    squeeze(gdshape(2,:,:))*(tN22.*(detJ.*w2D))) - ...
    squeeze(gdshape(1,:,:))*(dvNdx.*(detJ.*w2D)) - ...
    squeeze(gdshape(2,:,:))*(dvNdy.*(detJ.*w2D));

end