function [I11x1,I12x1,I21x1,I22x1,I11x2,I12x2,I21x2,I22x2] = ...
    ElementalStiffnessH1Mat(gdshape,shape,TpItQuad,...
    detJ,w2D)

% extra tensor components
[TpIt11,TpIt12,TpIt21,TpIt22] = ExtractTensorComponents(TpItQuad);

I11x1 = shape.t(:,:)*(squeeze(gdshape(1,:,:))'.*(TpIt11(:).*detJ.*w2D)) + ...
    shape.t(:,:)*(squeeze(gdshape(2,:,:))'.*(TpIt12(:).*detJ.*w2D)) + ...
    shape.t(:,:)*(squeeze(gdshape(1,:,:))'.*(TpIt11(:).*detJ.*w2D)) + ...
    shape.t(:,:)*(squeeze(gdshape(2,:,:))'.*(TpIt21(:).*detJ.*w2D));

I12x1 = shape.t(:,:)*(squeeze(gdshape(1,:,:))'.*(TpIt12(:).*detJ.*w2D)) + ...
    shape.t(:,:)*(squeeze(gdshape(2,:,:))'.*(TpIt22(:).*detJ.*w2D));

I21x1 = shape.t(:,:)*(squeeze(gdshape(1,:,:))'.*(TpIt21(:).*detJ.*w2D)) + ...
    shape.t(:,:)*(squeeze(gdshape(2,:,:))'.*(TpIt22(:).*detJ.*w2D));

I22x1 = zeros(size(I11x1));

I11x2 = zeros(size(I11x1));

I12x2 = shape.t(:,:)*(squeeze(gdshape(1,:,:))'.*(TpIt11(:).*detJ.*w2D)) + ...
    shape.t(:,:)*(squeeze(gdshape(2,:,:))'.*(TpIt12(:).*detJ.*w2D));

I21x2 = shape.t(:,:)*(squeeze(gdshape(1,:,:))'.*(TpIt11(:).*detJ.*w2D)) + ...
    shape.t(:,:)*(squeeze(gdshape(2,:,:))'.*(TpIt21(:).*detJ.*w2D));

I22x2 = shape.t(:,:)*(squeeze(gdshape(1,:,:))'.*(TpIt21(:).*detJ.*w2D)) + ...
    shape.t(:,:)*(squeeze(gdshape(2,:,:))'.*(TpIt22(:).*detJ.*w2D)) + ...
    shape.t(:,:)*(squeeze(gdshape(1,:,:))'.*(TpIt12(:).*detJ.*w2D)) + ...
    shape.t(:,:)*(squeeze(gdshape(2,:,:))'.*(TpIt22(:).*detJ.*w2D));

end

