function [I1,I2,I3,I4] = ElementalStiffnessH1(shape,TpItQuad,duNdx,dvNdx,duNdy,dvNdy,detJ,w2D)

[T11,T12,T21,T22] = ExtractTensorComponents(TpItQuad);

I1 = shape.t(:,:)*(T11.*duNdx.*(detJ.*w2D)) + ...
    shape.t(:,:)*(T12.*duNdy.*(detJ.*w2D)) + ...
    shape.t(:,:)*(T11.*duNdx.*(detJ.*w2D)) + ...
    shape.t(:,:)*(T21.*duNdy.*(detJ.*w2D));

I2 = shape.t(:,:)*(T11.*dvNdx.*(detJ.*w2D)) + ...
    shape.t(:,:)*(T12.*dvNdy.*(detJ.*w2D)) + ...
    shape.t(:,:)*(T12.*duNdx.*(detJ.*w2D)) + ...
    shape.t(:,:)*(T22.*duNdy.*(detJ.*w2D));

I3 = shape.t(:,:)*(T21.*duNdx.*(detJ.*w2D)) + ...
    shape.t(:,:)*(T22.*duNdy.*(detJ.*w2D)) + ...
    shape.t(:,:)*(T11.*dvNdx.*(detJ.*w2D)) + ...
    shape.t(:,:)*(T21.*dvNdy.*(detJ.*w2D));

I4 = shape.t(:,:)*(T21.*dvNdx.*(detJ.*w2D)) + ...
    shape.t(:,:)*(T22.*dvNdy.*(detJ.*w2D)) + ...
    shape.t(:,:)*(T12.*dvNdx.*(detJ.*w2D)) + ...
    shape.t(:,:)*(T22.*dvNdy.*(detJ.*w2D));

end