function [I1,I2,I3,I4] = ElementalStiffnessH1Fixed(shape,tN11,tN12,tN21,...
        tN22,duNdx,dvNdx,duNdy,dvNdy,detJ,w2D)


I1 = shape.t(:,:)*(tN11.*duNdx.*(detJ.*w2D)) + ...
    shape.t(:,:)*(tN12.*duNdy.*(detJ.*w2D)) + ...
    shape.t(:,:)*(tN11.*duNdx.*(detJ.*w2D)) + ...
    shape.t(:,:)*(tN21.*duNdy.*(detJ.*w2D));

I2 = shape.t(:,:)*(tN11.*dvNdx.*(detJ.*w2D)) + ...
    shape.t(:,:)*(tN12.*dvNdy.*(detJ.*w2D)) + ...
    shape.t(:,:)*(tN12.*duNdx.*(detJ.*w2D)) + ...
    shape.t(:,:)*(tN22.*duNdy.*(detJ.*w2D));

I3 = shape.t(:,:)*(tN21.*duNdx.*(detJ.*w2D)) + ...
    shape.t(:,:)*(tN22.*duNdy.*(detJ.*w2D)) + ...
    shape.t(:,:)*(tN11.*dvNdx.*(detJ.*w2D)) + ...
    shape.t(:,:)*(tN21.*dvNdy.*(detJ.*w2D));

I4 = shape.t(:,:)*(tN21.*dvNdx.*(detJ.*w2D)) + ...
    shape.t(:,:)*(tN22.*dvNdy.*(detJ.*w2D)) + ...
    shape.t(:,:)*(tN12.*dvNdx.*(detJ.*w2D)) + ...
    shape.t(:,:)*(tN22.*dvNdy.*(detJ.*w2D));

end